.github/workflows/lms_components_deploy_develop.yml
.github/workflows/lms_widgets_deploy_develop.yml

This PR is included updates for the development workflows on  micro-fronted. Since we're creating the Dev environment, we need to start using a unique directory list for microFE on dev. For this reason we are updating the dev workflows to call the Update Directory List action and keep the DL updated.
Link to jira: [CET-4173](https://celled.atlassian.net/browse/CET-4173)
[CET-4173]: https://celled.atlassian.net/browse/CET-4173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CET-4173 | SL | call Update Directory List for Dev

---

.github/workflows/services_build_deploy_dev.yml

This PR is introducing the new Dev workflow for micro-services. For now this workflow supports services built on nest.js
Ticket to Jira: [CET-418](https://celled.atlassian.net/browse/CET-4186)
[CET-418]: https://celled.atlassian.net/browse/CET-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CET-4186 | SL | new services Dev workflow

---

.github/workflows/lms_components_deploy_develop.yml
.github/workflows/lms_widgets_deploy_develop.yml

We are updating microFEs on dev to use the Dev cluster of micro-services

CET-4420 | SL | update REACT_APP_API_ENDPOINT to use Dev cluster

---

.github/workflows/services_build_deploy_dev.yml
.github/workflows/services_build_deploy_production.yml
.github/workflows/services_build_deploy_staging.yml

- Introduced the `Create .env File if Exists`  step to service pipelines to support new service deployments and their configuration management approach. 
- Pipelines were tested and verified 
**With the implementation of this modification, there will be no impact on existing legacy service deployments. This is because the newly introduced step is designed to be executed only under the specific condition that the .env.dev, .env.stg, and .env.prod environment files are present. If these files are not detected, the step will be bypassed, ensuring that the legacy service deployments remain unaffected.**

Feature/LMSNEXT-530 ENV file Step for New Services 

---

.github/workflows/models_library_publish.yml

A new workflow have been added for models.library
[LMSNEXT-747](https://celled.atlassian.net/browse/LMSNEXT-747)
[LMSNEXT-747]: https://celled.atlassian.net/browse/LMSNEXT-747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PR-LMSNEXT-747-JM

---

.github/workflows/services_build_deploy_dev.yml
.github/workflows/services_build_deploy_production.yml
.github/workflows/services_build_deploy_staging.yml

upgrade services workflow actions

LMSNEXT-574-JM

---

.github/workflows/lms_components_deploy_develop.yml
.github/workflows/lms_widgets_deploy_develop.yml
.github/workflows/services_build_deploy_dev.yml
.github/workflows/services_build_deploy_staging.yml

Changes for spinning up a dynamic badge server in workflow run to generate coverage badges.
Jira Ticket: [LMSNEXT-831](https://celled.atlassian.net/browse/LMSNEXT-831)
[LMSNEXT-831]: https://celled.atlassian.net/browse/LMSNEXT-831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LMSNEXT-831 | SR | Moving badge server to runner

---

.github/workflows/lms_components_deploy_develop.yml
.github/workflows/lms_widgets_deploy_develop.yml
.github/workflows/services_build_deploy_dev.yml

Changing Shields Server URL to Local and variable name improvements

LMSNEXT-831:Changing Shields Server URL to Local

---

.github/workflows/services_build_deploy_dev.yml

Fixing the mistake on one file with Variable name case.

LMSNEXT-831:Fixing Variable Name Case

---

.github/workflows/lms_components_deploy_staging.yml
.github/workflows/lms_widgets_deploy_staging.yml
.github/workflows/services_build_deploy_staging.yml

Adding Shields server startup to staging workflows

LMSNEXT-831 | SR | Adding shields server startup to staging workflow

---

.github/workflows/services_build_deploy_dev.yml

Adding changes in the micro services dev deploy to remove open-faas and support the new pipeline. Changes included.

LMSNEXT-981 | SR | update microservices wf

---

.github/workflows/services_build_deploy_dev.yml

Rollback mongoDB version due to an error in the pipeline using latest.

LMSNEXT-981 | SL | rollback mongoDB to 4.4

---

.github/workflows/services_build_deploy_dev_legacy.yml

First iteration for the Legacy workflow for old services.

LMSNEXT-992 | SL | new legacy workflow for old services

---

.github/workflows/services_build_deploy_dev_legacy.yml

LMSNEXT-992 | SL | second iteration

---

.github/workflows/services_build_deploy_dev_legacy.yml

LMSNEXT-992 | SL | third iteration

---

.github/workflows/services_build_deploy_dev_legacy.yml

LMSNEXT-992 | SL | fourth iteration

---

.github/workflows/services_build_deploy_dev_legacy.yml

LMSNEXT-992 | SL | sixth iteration

---

.github/workflows/services_build_deploy_dev_legacy.yml

LMSNEXT-992 | SL | seventh iteration

---

.github/workflows/services_build_deploy_dev.yml
.github/workflows/services_build_deploy_dev_legacy.yml

LMSNEXT-992 | SL | Eight iteration

---

.github/workflows/services_build_deploy_dev_legacy.yml

LMSNEXT-992 | SL | nineth iteration

---

.github/workflows/services_build_deploy_dev.yml
.github/workflows/services_build_deploy_dev_legacy.yml

LMSNEXT-992 | SL | tenth iteration

---

.github/workflows/services_build_deploy_dev.yml
.github/workflows/services_build_deploy_dev_legacy.yml

LMSNEXT-992 | SL | eleventh iteration

---

.github/workflows/services_build_deploy_dev.yml

- **troubleshooting npmrc - Try 1**
- **troubleshooting npmrc - Try 2**

Troubleshooting npmrc - Try 2

---

.github/workflows/services_build_deploy_dev.yml

- **troubleshooting npmrc - Try 1**
- **troubleshooting npmrc - Try 2**
- **troubleshooting npmrc - Try 3**

Troubleshooting npmrc - Try 3

---

.github/workflows/services_build_deploy_dev.yml

- **troubleshooting npmrc - Try 1**
- **troubleshooting npmrc - Try 2**
- **troubleshooting npmrc - Try 3**
- **troubleshooting npmrc - Try 4**

Troubleshooting npmrc - Try 4

---

.github/workflows/services_build_deploy_dev.yml
.github/workflows/services_build_deploy_dev_legacy.yml

- **troubleshooting npmrc - Try 1**
- **troubleshooting npmrc - Try 2**
- **troubleshooting npmrc - Try 3**
- **troubleshooting npmrc - Try 4**
- **debugging npmrc issue - Try 4**
- **clears docker build cache - Try 6**
- **Uses docker secrets in legacy WF**

Uses docker secrets in legacy WF

---

.github/workflows/services_build_deploy_dev.yml
.github/workflows/services_build_deploy_dev_legacy.yml
.github/workflows/services_build_deploy_production.yml
.github/workflows/services_build_deploy_production_legacy.yml
.github/workflows/services_build_deploy_staging.yml
.github/workflows/services_build_deploy_staging_legacy.yml
.github/workflows/services_singleNode_build_deploy_dev.yml
.github/workflows/services_singleNode_build_deploy_production.yml
.github/workflows/services_singleNode_build_deploy_staging.yml

- **Adds staging and produ WFs**
- **Adds GH WF for Single-Node services**

Adds supporting WFs for our new microservices runtime
